### ISSUE TITLE
[Feature Request] Allow ICR variable specification in tidyverse style

### ISSUE THREAD

**Issue by MarHai** [joon-e/tidycomm#11]
This is a great package that saves a lot of work. The nicest thing about it is its neat fit-in with the rest of the tidyverse. However, there's one little aspect that I am missing in that regard, is that the selection of the variables to be ICR'd is currently a `...` in its [variable list](https://github.com/joon-e/tidycomm/blob/master/R/icr.R#L64) rather than a [select-like ...](https://dplyr.tidyverse.org/reference/select.html).

What's more is that the current behavior can (!) yield large computational problems, for example when ICR'ing with groups. I assume this is due to the grouping variable. Take the following example:

```r
library(tidycomm)

# calculate ICR for all variables
# runs in no time
fbposts %>% 
  test_icr(post_id, coder_id)

# do the same but group by type
# takes quite a while
fbposts %>% 
  group_by(type) %>% 
  test_icr(post_id, coder_id)
```

One way to circumvent this is to exclude the grouping variable, but this can only be done without grouping (because grouping variables are always included):

```r
fbposts %>% 
  filter(type == 'photos') %>% 
  select(-type) %>%
  test_icr(post_id, coder_id)
```

The much nicer thing to do would be the following (but this is currently not possible):

```r
fbposts %>% 
  group_by(type) %>%
  test_icr(post_id, coder_id, -type)
```

To be fair, I am not entirely sure whether this is actually a calculation bug that yields the computational overload or whether this is really a feature request as in "I want `-type`", but it certainly is something to discuss :)

Thanks,
Mario

**Comment by vogelgesang** [comment]
I totally agree with @MarHai - great package. Could you add 

LowerCI95 = .data$M - qt(0.975,df=.data$N-1)*.data$SD/sqrt(.data$N)
UpperCI95 = .data$M + qt(0.975,df=.data$N-1)*.data$SD/sqrt(.data$N)

to the describe function?

I know there are many more ways to compute CIs such as in

https://www.rdocumentation.org/packages/rcompanion/versions/2.3.25/topics/groupwiseMean

- but whatever suits best...

Thanks,
Jens

**Comment by joon-e** [comment]
> I totally agree with @MarHai - great package. Could you add
> 
> LowerCI95 = .data$M - qt(0.975,df=.data$N-1) * .data$SD/sqrt(.data$N)
> UpperCI95 = .data$M + qt(0.975,df=.data$N-1) * .data$SD/sqrt(.data$N)
> 
> to the describe function?
> 
> I know there are many more ways to compute CIs such as in
> 
> https://www.rdocumentation.org/packages/rcompanion/versions/2.3.25/topics/groupwiseMean
> 
> * but whatever suits best...
> 
> Thanks,
> Jens

Thanks! I've opened up a new issue for the feature request :)

**Comment by joon-e** [comment]
> This is a great package that saves a lot of work. The nicest thing about it is its neat fit-in with the rest of the tidyverse. However, there's one little aspect that I am missing in that regard, is that the selection of the variables to be ICR'd is currently a `...` in its [variable list](https://github.com/joon-e/tidycomm/blob/master/R/icr.R#L64) rather than a [select-like ...](https://dplyr.tidyverse.org/reference/select.html).
> 
> What's more is that the current behavior can (!) yield large computational problems, for example when ICR'ing with groups. I assume this is due to the grouping variable. Take the following example:
> 
> ```r
> library(tidycomm)
> 
> # calculate ICR for all variables
> # runs in no time
> fbposts %>% 
>   test_icr(post_id, coder_id)
> 
> # do the same but group by type
> # takes quite a while
> fbposts %>% 
>   group_by(type) %>% 
>   test_icr(post_id, coder_id)
> ```
> 
> One way to circumvent this is to exclude the grouping variable, but this can only be done without grouping (because grouping variables are always included):
> 
> ```r
> fbposts %>% 
>   filter(type == 'photos') %>% 
>   select(-type) %>%
>   test_icr(post_id, coder_id)
> ```
> 
> The much nicer thing to do would be the following (but this is currently not possible):
> 
> ```r
> fbposts %>% 
>   group_by(type) %>%
>   test_icr(post_id, coder_id, -type)
> ```
> 
> To be fair, I am not entirely sure whether this is actually a calculation bug that yields the computational overload or whether this is really a feature request as in "I want `-type`", but it certainly is something to discuss :)
> 
> Thanks,
> Mario

Thanks! As I see it, there a two related issues here:

Grouping:
I guess the easiest way would be to exclude all grouping variables from the ICR calculations, so 

```r
 fbposts %>% 
 group_by(type) %>%
 test_icr(post_id, coder_id)
```
would lead to ICR per level of `type` of all test variables (excluding `type`).

Tidyselect:
Make tidyselect helpers available, so for example
 
```r
 fbposts %>% 
 test_icr(post_id, coder_id, -type)
```
would lead to ICR of all test variables (excluding `type`).

Right?

**Comment by MarHai** [comment]
I guess the second would help to "fix" the first one if there's a hint in the docs of test_icr that grouping may require excluding the grouping vars. Not sure how other tidyverse elements handle groups, though.

**Comment by joon-e** [comment]
# f5a8fbcb7f31a975189e6c61ef19eb2b2be589b1

Tidyselect helpers should work now. Handling grouped data must have to wait for another time, but a warning is displayed for grouped data now (and groups are removed to avoid said calculation bug)
