### ISSUE TITLE
unianova cannot handle spaces in column names

### ISSUE THREAD

**Issue by MarHai** [joon-e/tidycomm#12]
Hi,

when handling column names that include a space (I know, bad practice, but still ...), `unianova` dies with a rather cryptic error message. This is presumably happening in https://github.com/joon-e/tidycomm/blob/7de8942c0c83a5f1453d2f101909ce0e140ad0ec/R/unianova.R#L70

Here is an example, working (first) and not working (second).
```
WoJ %>% 
  select(employment, autonomy_selection) %>% 
  unianova(employment)

WoJ %>% 
  select(employment, `autonomy selection` = autonomy_selection) %>% 
  unianova(employment)
```

**Comment by joon-e** [comment]
# f5a8fbcb7f31a975189e6c61ef19eb2b2be589b1
