### ISSUE TITLE
‘MBESS’-package not installed/loaded with tidycomm

### ISSUE THREAD

**Issue by xvariable** [joon-e/tidycomm#13]
Hi there,

thank you for making this, it is aweome, especially for teaching! I discovered that there is a dependency wich is not installed/loaded with the package. ‘MBESS’-package is missing (see below). 

It would be great if you could fix that, because this is a possible source of frustration in undergrad classes ;)

Best, 
Julia

```r
WoJ %>% 
     add_index(ethics_mean, ethics_1, ethics_2, ethics_3, ethics_4) %>% 
     get_reliability()
Fehler in loadNamespace(name) : there is no package called ‘MBESS’
```

**Comment by joon-e** [comment]
Hi Julia,

thank you! This is kind of a weird one, as `MBESS` is listed as a dependency and I cannot replicate this issue on my own machines or Travis CI. Could you please provide me with some system information?
