### ISSUE TITLE
Get test_icr to work with grouped data

### ISSUE THREAD

**Issue by JBGruber** [joon-e/tidycomm#17]
Hey @joon-e, great package! I'm really happy I can finally ditch my previous approach and work directly with tidy data when calculating icr.

I just noticed the message `Warning message: test_icr does not support grouped data yet. Groups will be dropped.`. If you are looking for a hint on how you can implement this, [you can check out an answer I just posted over at SO](https://stackoverflow.com/a/71587952/5028841). Feel free to ignore if you have a better idea in mind though...

``` r
df2 <- data.frame(
  "group" = c(1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 5), 
  "R1"    = c(1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0),
  "R2"    = c(1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0),
  "R3"    = c(1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0))

library(tidyverse)
library(tidycomm)
df2 %>% 
  mutate(post_id = row_number()) %>% 
  pivot_longer(R1:R3, names_to = "coder_id", values_to = "code") %>%
  group_by(group) %>% 
  group_map(.f = function(.x, .y) {
    out <- test_icr(.x, unit_var = post_id, coder_var = coder_id, code)
    add_column(out, group = .y$group, .before = 1L)
  }) %>% 
  bind_rows()
#> # A tibble: 5 × 9
#>   group Variable n_Units n_Coders n_Categories Level   Agreement Holstis_CR
#>   <dbl> <chr>      <int>    <int>        <int> <chr>       <dbl>      <dbl>
#> 1     1 code           4        3            2 nominal     0.5        0.667
#> 2     2 code           3        3            2 nominal     0.667      0.778
#> 3     3 code           4        3            2 nominal     1          1    
#> 4     4 code           4        3            2 nominal     0.5        0.667
#> 5     5 code           5        3            2 nominal     0.8        0.867
#> # … with 1 more variable: Krippendorffs_Alpha <dbl>
```

<sup>Created on 2022-03-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by joon-e** [comment]
Dear Johannes, thanks for the kind words!

I have actually played around a bit with `group_map()` already, so this seems to be an easy way to implement this feature. I'll try to do this the next time I work on the package, although I am a bit swamped with work at the moment, what with the semester start and all. But hopefully within the next couple of weeks.

Best

Julian

**Comment by LKobilke** [comment]
Feature request included. Closing this issue.
