### ISSUE TITLE
one-sample t test ("location test")

### ISSUE THREAD

**Issue by MarHai** [joon-e/tidycomm#26]
Our curriculum includes a [one-sample t-test](https://de.wikipedia.org/wiki/Einstichproben-t-Test) (also known as [location test](https://en.wikipedia.org/wiki/Location_test)) that tidycomm currently does not support. The suggestion here is to include this test with the tidycomm as well.

The statistical process is straight-forward in that a mean is compared to the general population's location of that value ("Erwartungswert" My, 𝜇) via the t distribution and a set confidence level. The base function `t.test` does that (`t.test(x, my)`).

A to-be-discussed suggestion for implementation could be to extend the current `t_test` as follows:

- `group_var` gets a new description, for example "group variable (column name) to specify where to split two samples (two-sample t-test) or which variable to compare a one-sample t-test on"
- `test_var` receives additional description, for example "Also leave empty for one-sample t-tests."
- `my` is added as an optional parameter that, if specified, yields a one-sample t-test

This way, all the following codes should work (all but the last of which have not been edited from the current code):

```r
WoJ %>% 
  t_test(temp_contract, 
         autonomy_selection, autonomy_emphasis)

WoJ %>% 
  t_test(temp_contract)

WoJ %>% 
  t_test(employment, 
         autonomy_selection, autonomy_emphasis, 
         levels = c("Full-time", "Freelancer"))

WoJ %>%
  t_test(trust_parties, 
         my = 1.48)
```

**Comment by LKobilke** [comment]
If we don't want to create an additional one-sample t-test function, then I think this is the best approach!

By the way, if we decide to always subsume all subtypes of a test in the main function and differentiate them by parameters, then of course we should also decide to use `correlate(partial = TRUE)` in #27. However, then we will have to rethink `unianova()` at some point.
