### ISSUE TITLE
correlate(): Add sample size output and comparison variable option

### ISSUE THREAD

**Issue by LKobilke** [joon-e/tidycomm#47]
Two requests for `correlate()`:

1. Include sample size ('n') in the output. Or give an option to include it (like in SPSS).
2. Allow specifying a comparison variable (= SPSS's "correlate with") to reduce output size. Currently, the output can be overwhelming.

**Comment by LKobilke** [comment]
**1. First request, include n:**
By default, `correlate()` will now include sample size:
![image](https://github.com/joon-e/tidycomm/assets/100684892/f9d21a0d-bd90-4b5d-8c83-d788fbef9892)

And to_correlate_matrix() provides the sample size as a header if only two variables are specified:
![image](https://github.com/joon-e/tidycomm/assets/100684892/adc96e4f-f2a9-4663-9023-56967b9b8837)

**2. Second request, correlate with focus variable:**
I've implemented a "with" parameter in the `correlate()` function that takes a focus variable that everything else is correlated against:

![image](https://github.com/joon-e/tidycomm/assets/100684892/a06fbee7-c4b8-46f9-a0d1-46c4ce8c91f7)

Also works without specifying vars:

![image](https://github.com/joon-e/tidycomm/assets/100684892/4335a499-ebd9-4e20-be78-d3e77a376bc4)

Specifiyng both the `partial `and the `with `paramter in a `correlate()` will raise an error:

![image](https://github.com/joon-e/tidycomm/assets/100684892/c9c717e6-546a-4274-8e89-90f482e34484)

**Comment by MarHai** [comment]
Great addition! 

My only criticism here is, again, on the string format of the `with` parameter -- the remainder of the package always works with dplyr vocabulary. We should stick to that, I think.
